### ISSUE TITLE
Some crates hides playerLives Text

### ISSUE THREAD

**Issue by santiHerranz** [KilledByAPixel/SpaceHuggers#1]
![imagen](https://user-images.githubusercontent.com/961911/134380158-97504ba5-2dee-4b30-8da7-1523fd08dcf7.png)

**Comment by KilledByAPixel** [comment]
Yes, thank you for posting this! I am surprised more people didn't notice but it's easy to get lost in the action. This is a small tradeoff I made so the game runs smoothly in Firefox and other browsers that are slow to composite webgl canvases onto 2d canvases. It does not happen on Chrome which runs fantastic!

It can be fixed of course, but not without adding more code. In the engine this is called glOverlay mode. Which makes the webgl canvas visible and just positions it on top of the 2d canvas. The fix requires another canvas or div to be a higher z-index then the gl canvas so it appears on top. Either that or wait for Firefox to optimize their code! I will fix it locally as I continue to build out the game, but I this repo is pretty much just for the js13k build.

You can check out how it runs without this by setting glOverlay to false at the top of app.js

https://github.com/KilledByAPixel/SpaceHuggers/blob/main/app.js
